### ISSUE TITLE
Question regarding the GGD loss

### ISSUE THREAD

**Issue by Aonnghus** [ExplainableML/UncertaintyAwareCycleConsistency#2]
Hi,

First of all, thank you for this great work! It is really a nice idea to relax the Gaussian/Laplace assumption by taking a more general distribution.

However, I have got a question regarding how you implemented the loss.
In the `bayeGen_loss` method of `losses.py`, you compute `resi = (resi*factor*out_beta).clamp(min=1e-6, max=50)`.
But in the formula of the loss derived from the NLL in your paper, β is used as a power over `resi`, like `(resi*factor)**out_beta`.
Is there a kind of implementation trick here?

**Comment by udion** [comment]
Check the appendix here (Eq.16 and its derivation): https://arxiv.org/pdf/2307.00398.pdf

In practice, the Taylor series approximation makes training more stable.
